In [1]:
import numpy as np

In [2]:
array1 = np.arange(15,41)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

In [4]:
array2 = np.arange(10,26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
even_array1 = np.arange(2,20,2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
even_array2 = np.arange(34,42,2)
even_array2

array([34, 36, 38, 40])

In [18]:
stacked_matrix = np.stack((even_array1[:4], even_array2))
stacked_matrix

array([[ 2,  4,  6,  8],
       [34, 36, 38, 40]])

In [19]:
matrix_66 = np.reshape(np.arange(0,36), shape=(6,6))
matrix_66

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [20]:
matrix_66[2,1]

np.int64(13)

In [22]:
matrix_normal_dist = np.random.randn(5,2)
matrix_normal_dist

array([[-1.17542948, -0.32757851],
       [ 1.04428553,  0.02872088],
       [ 0.21765587,  0.83922312],
       [-0.40376288, -0.03713841],
       [-0.99960347, -2.05355283]])

In [23]:
matrix_normal_dist[-1,-1]

np.float64(-2.053552832411064)

In [25]:
np.min(matrix_normal_dist).round(2)

np.float64(-2.05)

In [26]:
np.max(matrix_normal_dist).round(2)

np.float64(1.04)

In [27]:
np.std(matrix_normal_dist)

np.float64(0.8882897424750704)

In [28]:
np.var(matrix_normal_dist)

np.float64(0.789058666586427)

In [29]:
np.mean(matrix_normal_dist)

np.float64(-0.28671801844269756)