In [1]:
import numpy as np # importing the numpy library

In [2]:
# Creating list
my_list = [1,2,3]
my_array = np.array(my_list)
my_array # print +ve tuple

array([1, 2, 3])

In [3]:
type(my_list)

list

In [4]:
type(my_array)

numpy.ndarray

In [5]:
my_array = np.array([1,2,3])
print(my_array)

[1 2 3]


### Create multidimensional array

In [6]:
list_of_lists = np.array([[1,2,3], [4,5,6], [7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
list_of_lists.shape

(3, 3)

In [8]:
# Return evenly spaced value with a given interval
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)  # generating number in array from 0 to 10 with interval 2

array([0, 2, 4, 6, 8])

In [11]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


### np.zeros(), np.ones(), np.eye(), len(np.array)

In [12]:
zero_array = np.zeros(100)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(10) # generate 2d array with diagonal value 1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
len(np.arange(0,50))

50

In [16]:
len(np.ones(shape=(3,3)))

3

### np.reshape()

In [17]:
my_array = np.arange(0,50)
np.reshape(my_array, (5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
np.linspace(0,7,20) # return 20 evenly spaced values 0 to 7, values in float

array([0.        , 0.36842105, 0.73684211, 1.10526316, 1.47368421,
       1.84210526, 2.21052632, 2.57894737, 2.94736842, 3.31578947,
       3.68421053, 4.05263158, 4.42105263, 4.78947368, 5.15789474,
       5.52631579, 5.89473684, 6.26315789, 6.63157895, 7.        ])

### np.resize()

In [19]:
np.resize(np.linspace(0,7,20), (2,10))

array([[0.        , 0.36842105, 0.73684211, 1.10526316, 1.47368421,
        1.84210526, 2.21052632, 2.57894737, 2.94736842, 3.31578947],
       [3.68421053, 4.05263158, 4.42105263, 4.78947368, 5.15789474,
        5.52631579, 5.89473684, 6.26315789, 6.63157895, 7.        ]])

In [20]:
np.resize(np.linspace(0,7,20), (2,8))

array([[0.        , 0.36842105, 0.73684211, 1.10526316, 1.47368421,
        1.84210526, 2.21052632, 2.57894737],
       [2.94736842, 3.31578947, 3.68421053, 4.05263158, 4.42105263,
        4.78947368, 5.15789474, 5.52631579]])

## Generate some random values

### np.random.rand(), np.random.randn(), np.random.randin()

In [34]:
np.random.rand(3,2)

array([[0.97574045, 0.64768642],
       [0.16369635, 0.7417213 ],
       [0.84874986, 0.29100661]])

In [35]:
np.mean(np.random.rand(3,2))

np.float64(0.4666116408958378)

In [36]:
np.random.randn(3,3)

array([[-0.22942293,  0.33468137,  0.57543067],
       [-0.46740682,  0.57166523, -0.55788823],
       [ 1.61878866, -0.33923321, -1.21487882]])

In [37]:
np.mean(np.random.randn(3,3))

np.float64(-0.1747316023313946)

In [38]:
np.random.randint(4, 100, 10)

array([65, 35, 82, 72, 92, 85, 75, 19, 26, 22])

In [40]:
np.random.randint(0, 5, size=(2,3))

array([[0, 4, 0],
       [0, 2, 4]])

## Indexing and Slicing

In [41]:
random_array = np.random.randint(4,15,10)
random_array

array([11,  6, 11,  7, 11,  5, 12,  8, 14, 11])

In [42]:
random_array[3]

np.int64(7)

In [43]:
random_array[-2]

np.int64(14)

In [44]:
random_array[3:7]

array([ 7, 11,  5, 12])

In [45]:
random_array[2:]

array([11,  7, 11,  5, 12,  8, 14, 11])

In [46]:
random_array[5:-2]

array([ 5, 12,  8])

In [48]:
random_array_2 = np.reshape(random_array, shape=(5,2))
random_array_2

array([[11,  6],
       [11,  7],
       [11,  5],
       [12,  8],
       [14, 11]])

In [49]:
matrix_2d = np.reshape(np.arange(64), shape=(8,8))
matrix_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [51]:
matrix_2d[:,3]

array([ 3, 11, 19, 27, 35, 43, 51, 59])

In [52]:
matrix_2d[2:4, 5:7]

array([[21, 22],
       [29, 30]])

In [53]:
matrix_2d[2,3]

np.int64(19)

In [54]:
matrix_2d[4,2:5]

array([34, 35, 36])

In [55]:
matrix_2d[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [56]:
matrix_2d[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

### Conditional indexing

In [59]:
matrix_2d > 25

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [60]:
matrix_2d[matrix_2d>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63])

In [66]:
matrix_2d[(matrix_2d > 25) & (matrix_2d < 35)]

array([26, 27, 28, 29, 30, 31, 32, 33, 34])

### Creating Copy

In [69]:
copied_matrix_1 = matrix_2d[3:, 3:]
copied_matrix_1

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [70]:
copied_matrix_2 = matrix_2d.copy()
copied_matrix_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

## NumPy Dataframes

In [77]:
file_path = "/Users/vishalsaxena/Documents/DS_Workspace/ds_bootcamp/data/"
! cat '/Users/vishalsaxena/Documents/DS_Workspace/ds_bootcamp/data/raw/Olympics.csv'

Country,Gold,Silver,Bronze,Total
USA,39,41,33,113
China,38,32,18,88
Russia,20,28,23,71
UK,22,21,22,65
Germany,10,11,16,37


In [86]:
import pandas as pd
import os
data = pd.read_csv(os.path.join(file_path, 'raw/Olympics.csv'))
data.head()

Country  Gold  Silver  Bronze  Total
0      USA    39      41      33    113
1    China    38      32      18     88
2   Russia    20      28      23     71
3       UK    22      21      22     65
4  Germany    10      11      16     37

In [89]:
df = data.copy()

In [90]:
df['Country']

0        USA
1      China
2     Russia
3         UK
4    Germany
Name: Country, dtype: object